5 Desafios - Yasmin
IFSP-HTO/FisicaGames pull request #2
Opened 2019-06-07 23:32 UTC by YasminDeodato

**Desafio 1:** hello_goodbye.py
Proposta: ao clicar no botão hello ou goodbye mostra texto correspondente.
Disponível em: http://www.codeskulptor.org/#user46_ykK8brwZ9y_8.py

**Desafio 2:** colors.py
Proposta: clicar nos botões azul e vermelho para manipular variável _color_ e mostrar na tela.
Disponível em: http://www.codeskulptor.org/#user46_6fWg1Sa0oo_4.py

**Desafio 3** count.py
Proposta: manipular valores de _count_, através dos botões e mostrar na tela.
Disponível em: http://www.codeskulptor.org/#user46_Gz2VVaidPK_2.py

**Desafio 4** input_show.py
Proposta: mostrar na tela o texto obtido a partir de um campo de entrada.
Disponível em: http://www.codeskulptor.org/#user46_8K4x6ADIom_2.py

**Desafio 5** rpsls_input.py
Proposta: game rpsls com entrada do usuário validada a partir da interface.
Disponível em: http://www.codeskulptor.org/#user46_HET62s8d7F_5.py

2019-06-14 18:22 UTC, flaviobarros requested changes
Yasmin, por favor inclua nos comentários do cabeçalho os links para o Codeskulptor para que eu possa testar. É só adicionar as alterações no seu próprio repositório que elas serão refletidas aqui. Assim que você fizer a alteração eu aceito o pull request.

2019-06-15 13:25 UTC, YasminDeodato commented on Yasmin/colors.py
> +import simplegui
**Desafio 2:** colors.py
Proposta: clicar nos botões azul e vermelho para manipular variável color e mostrar na tela.
Disponível em: http://www.codeskulptor.org/#user46_6fWg1Sa0oo_4.py

2019-06-15 13:25 UTC, YasminDeodato commented on Yasmin/count.py
> +import simplegui
**Desafio 1:** hello_goodbye.py
Proposta: ao clicar no botão hello ou goodbye mostra texto correspondente.
Disponível em: http://www.codeskulptor.org/#user46_ykK8brwZ9y_8.py

2019-06-15 13:26 UTC, YasminDeodato commented on Yasmin/hello_goodbye.py
> +import simplegui
**Desafio 1:** hello_goodbye.py
Proposta: ao clicar no botão hello ou goodbye mostra texto correspondente.
Disponível em: http://www.codeskulptor.org/#user46_ykK8brwZ9y_8.py

2019-06-15 13:26 UTC, YasminDeodato commented on Yasmin/input_show.py
> +import simplegui
**Desafio 4:** input_show.py
Proposta: mostrar na tela o texto obtido a partir de um campo de entrada.
Disponível em: http://www.codeskulptor.org/#user46_8K4x6ADIom_2.py

2019-06-15 13:28 UTC, YasminDeodato commented on Yasmin/rpsls_input.py
> +rpsls("tesoura")"""
**Desafio 5:** rpsls_input.py
Proposta: game rpsls com entrada do usuário validada a partir da interface.
Disponível em: http://www.codeskulptor.org/#user46_HET62s8d7F_5.py

2019-06-17 13:41 UTC, flaviobarros commented on Yasmin/rpsls_input.py
> +rpsls("tesoura")"""
Yasmin, é para colocar como comentário no próprio código. Aqui onde você colocou, assim que eu aceitar o pull request, vai sumir. Tem que estar no próprio código fonte.

2019-06-19 10:45 UTC, flaviobarros approved these changes

2019-06-19 10:45 UTC, merged