Exercícios no Canvas
IFSP-HTO/FisicaGames pull request #6
Opened 2019-08-17 15:56 UTC by PauloV231

Exercício 1: https://py3.codeskulptor.org/#user303_UBUK5gFjy1xtvza.py
Exercício 2: https://py3.codeskulptor.org/#user303_7EdKYUG3pY7tBor.py
Exercício 3: https://py3.codeskulptor.org/#user303_cjrLd5R7LIzY0up.py
Exercício 4: https://py3.codeskulptor.org/#user303_eRdCleREJVp0Xdn.py
Exercício 5: https://py3.codeskulptor.org/#user303_eMWFafuvWhkUQMs.py

2019-08-30 19:22 UTC, PauloV231 commented
Professor, nesse ultimo problema do cronometro, estou com um problema que quando a função time é iniciado, ele da um erro, o programa não esta completo, mas está dando esse erro, nessa versão eu so queria saber como vai funcionar a mensagem no canvas, mas mesmo uma mensagem simples, ele da o erro assim que passa 1 segundo

2019-08-30 19:24 UTC, PauloV231 commented
Eu gostaria de saber se você pode me ajudar, acho que o problema é que quando ele vai executar a função draw_handler pela segunda vez, ele bão consegue, pois já a algo escrito naquele lugar, naquela coordenada, mas eu não sei como resolver

2019-08-30 19:38 UTC, flaviobarros commented
Oi Paulo vou dar uma olhada e já te dou um retorno.

2019-08-30 19:40 UTC, flaviobarros commented on Paulo/Canvas_X
> +    pass
O pass não é necessário pois é uma palavra usada na função somente para terminar a função. Como vc tem um return você não precisa.

2019-08-30 19:40 UTC, flaviobarros commented on Paulo/Circlo_Aumenta_Diminui
> +    pass
O pass não é necessário pois é uma palavra usada na função somente para terminar a função. Como vc tem um return você não precisa.

2019-08-30 19:54 UTC, flaviobarros commented
Paulo qual é o link do arquivo que você disse que está com um problema? Não estou achando.

2019-08-31 16:33 UTC, PauloV231 commented
Eu esqueci de colocar o link:
https://py3.codeskulptor.org/#user304_3G32Gam0drMbSml.py

2019-09-06 13:58 UTC, flaviobarros requested changes
Tem um bug no seu código pois quando eu vou diminuindo o raio da bola ela pode assumir um valor negativo e o programa para.

2019-09-06 13:58 UTC, flaviobarros commented on Paulo/Circlo_Aumenta_Diminui
> +    pass
O pass não é necessário pois é uma palavra usada na função somente para terminar a função. Como vc tem um return você não precisa.

2019-09-06 13:58 UTC, flaviobarros commented on Paulo/Circlo_Aumenta_Diminui
> +    pass
O pass não é necessário pois é uma palavra usada na função somente para terminar a função. Como vc tem um return você não precisa.

2019-09-06 13:58 UTC, flaviobarros commented on Paulo/Cronometro
> +    pass
O pass não é necessário pois é uma palavra usada na função somente para terminar a função. Como vc tem um return você não precisa.

2019-09-06 13:58 UTC, flaviobarros commented on Paulo/Cronometro
> +    pass
O pass não é necessário pois é uma palavra usada na função somente para terminar a função. Como vc tem um return você não precisa.

2019-09-06 13:58 UTC, flaviobarros commented on Paulo/Cronometro
> +    pass
O pass não é necessário pois é uma palavra usada na função somente para terminar a função. Como vc tem um return você não precisa.

2019-09-06 13:58 UTC, flaviobarros commented on Paulo/Cronometro
> +    pass
O pass não é necessário pois é uma palavra usada na função somente para terminar a função. Como vc tem um return você não precisa.

2019-09-06 13:58 UTC, flaviobarros commented on Paulo/Cronometro
> +    pass
O pass não é necessário pois é uma palavra usada na função somente para terminar a função. Como vc tem um return você não precisa.

2019-09-06 13:58 UTC, flaviobarros commented on Paulo/Cronometro
> +    pass
O pass não é necessário pois é uma palavra usada na função somente para terminar a função. Como vc tem um return você não precisa.

2019-09-06 13:58 UTC, flaviobarros commented on Paulo/Isso_é_Fácil
> +    pass
O pass não é necessário pois é uma palavra usada na função somente para terminar a função. Como vc tem um return você não precisa.

2019-09-06 13:58 UTC, flaviobarros commented on Paulo/Minutos_Segundos
> +    pass
O pass não é necessário pois é uma palavra usada na função somente para terminar a função. Como vc tem um return você não precisa.

2019-09-06 20:29 UTC, PauloV231 commented
Professor, acredito que eu tenha arrumado todos os bugs e erros

2019-09-07 12:03 UTC, PauloV231 commented
Professor, já fiz a tarefa sobre as listas, mas não consegui fazer os itens da lista aparecer uma embaixo da outra

2019-09-07 15:51 UTC, flaviobarros reviewed
Uma outra coisa: quando você for adicionar uma nova tarefa e já tiver um pull request aberto, abra outro novo porque senão fica tudo misturado e fica mais complicado de finalizar e revisar.

2019-09-07 15:51 UTC, flaviobarros commented on Paulo/CriarLista
> +def removeTarefaNumero(num):
Tem um bug aqui: quando você tenta remover pelo número, se você tenta o mesmo número várias vezes ele para o programa porque você tentou remover um item fora da lista. Tem que consertar isso.

2019-09-07 15:51 UTC, flaviobarros commented on Paulo/CriarLista
> +def addTarefa(texto):
Tem um bug aqui: você consegue adicionar a mesma tarefa mais uma vez: ele não deveria permitir adicionar a mesma tarefa.

2019-09-09 03:36 UTC, flaviobarros requested changes

2019-09-09 03:36 UTC, flaviobarros commented on Paulo/CriarLista
> +    canvas.draw_text(string, [50,50], 30, 'White')
A única coisa faltou mesmo é que a impressão precisa ser feita embaixo e não na frente. Você precisa modificar o draw_text para isso. Eu queria um efeito semelhante ao que eu coloquei no exemplo.

2019-09-09 21:33 UTC, merged